course_app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("create", createCourse , name="course_create"),
    path("update/<int:courseId>", updateCourse ,name="course_update"),
    path("detail/<int:courseId>", getCourseDetail,name="course_detail"),
    path("list", getCourseList , name="course_list"),
    path('delete/<int:courseId>', courseDelete, name ='course_delete'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path,include
from .view import *

urlpatterns = [
    path('', home_screen, name='home'),
  
    path('admin/', admin.site.urls),
    path("school/",include("school_app.urls")),
    path("course/",include("course_app.urls")),

]

handler404 ='my_project.view.error_404_view'

school_app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("list", getSchoolList ,name="school_list"),
    path("detail/<int:schoolId>", getSchoolDetail,name="school_detail"),
    path("create", addSchool ,name="school_create"),
    path("update/<int:schoolId>", updateSchool ,name="school_update"),
    path('delete/<int:schoolId>', schoolDelete, name ='school_delete'),
 
]

course_app/models.py
from django.db import models
from school_app.models import School
from django.core.validators import MinValueValidator, MaxValueValidator

class Course(models.Model):
    name = models.CharField(max_length=20)
    coordinator = models.CharField(max_length=20)
    credits = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(360)]) 
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='courses')

    def __str__(self):
        return self.name

school_app/models.py
from django.db import models

class School(models.Model):
    name = models.CharField(max_length=20)
    head_of_school = models.CharField(max_length=20)
    location = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

course_app/forms.py
from django import forms
from .models import Course

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'coordinator', 'credits', 'school']

school_app/forms.py
from django import forms

from .models import School

class SchoolForm(forms.ModelForm):
       class Meta:
        model = School
        fields = ['name','head_of_school','location']

course_app/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Course
from .forms import CourseForm

# Create your views here.

app_name = 'course_app'
def createCourse(request):
    if request.method == 'POST':
        course_form = CourseForm(request.POST)
        if course_form.is_valid():
            course = course_form.save(commit= False)
            course.save()
            return redirect('/course/detail/{}'.format(course.id))  # Redirect to a success page or another view
    else:
        school_form = CourseForm()
    return render(request, 'course_add.html', {'course_form': school_form})


def getCourseDetail(request,courseId):
    courseDetail = get_object_or_404(Course, pk=courseId)    
    return render(request, 'course_detail.html',{"courseDetails":courseDetail})


def getCourseList(request):
    courseList = Course.objects.all()
    context ={
        'courseList':courseList
    }
    return render(request, 'course_list.html',context)


def updateCourse (request,courseId):
    course_instance = get_object_or_404(Course, pk=courseId)
    if request.method == 'POST':
        form = CourseForm(request.POST, instance=course_instance)
        if form.is_valid():
            form.save()
            return redirect('/course/detail/{}'.format(course_instance.id))  # Redirect to a success URL
    else:
        form = CourseForm(instance=course_instance)  # Populate the form with the instance data
    return render(request, 'course_edit.html', {'course_form': form})


def courseDelete(request,courseId):
    if request.method == 'POST':
      course = get_object_or_404(Course, pk=courseId)
      course.delete()
      return redirect('/course/list')
    else:
        return redirect('/course/list')

school_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import School
from course_app.models import Course
from .forms import SchoolForm 


# Create your views here.

app_name = 'school_app'
def addSchool (request):
    if request.method == 'POST':
        school_form = SchoolForm(request.POST)
        if school_form.is_valid():
            
            school = school_form.save(commit= False)
    
      
        return redirect('/school/detail/{}'.format(school.id))
    else:
        form = SchoolForm()
        return render(request, 'school_add.html',{'school_form': form})
    
def getSchoolList (request):
    schools = School.objects.all()
    context ={
        'schools':schools
    }
    return render(request, 'school_list.html',context)

def getSchoolDetail(request, schoolId):
    school = get_object_or_404(School, pk=schoolId)
    courses = Course.objects.filter(school=schoolId)
    return render(request, 'school_detail.html', {"schoolDetails": school, "courses": courses})
    
def updateSchool (request,schoolId):
    school_instance = get_object_or_404(School, pk=schoolId)
    if request.method == 'POST':
        form = SchoolForm(request.POST, instance=school_instance)
        if form.is_valid():
            form.save()
            return redirect('/school/detail/{}'.format(school_instance.id))  # Redirect to a success URL
    else:
        form = SchoolForm(instance=school_instance)  # Populate the form with the instance data
    return render(request, 'school_edit.html', {'school_form': form})
    
def schoolDelete(request,schoolId):
    if request.method == 'POST':
      school = get_object_or_404(School, pk=schoolId)
      school.delete()
      return redirect('/school/list')
    else:
        return redirect('/school/list')
    

course_app/templates/course_add.html
{% extends 'base.html'%} {% load bootstrap %} {% block body_block %}


<h2 class="text-center">Add Course</h2>
<div class="container-fluid d-flex justify-content-center">
  <div class="container d-flex pt-4 ">
    <form
      action=""
      id="form"
      method="POST"
      class="w-100 w-lg-75 "
   
      enctype="multipart/form-data"
    >
      {% csrf_token %} {{course_form|bootstrap_horizontal}}
      <button type="submit" class="btn btn-primary mt-2  text-center mx-auto" name="post_submit">
        Add Course
      </button>
    </form>

    <div class="col-4" style={height:"100vh"}>
      <img
       class="img-fluid object-fit-cover"
        src="https://plus.unsplash.com/premium_photo-1663051241451-709fa4de55bc?q=80&w=2950&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
      />
    </div>
  </div>
</div>

{% endblock body_block %}

course_app/templates/course_detail.html
{% extends 'base.html'%} {% block body_block %}
<div class="container">
  <h2>Course Detail Page</h2>
  <div
    class="container flex-row flex card p-2 my-3 gap-5 position-relative w-full"
  >
    <div class="">
      <p class="text-black">Name :</p>
      <p>Coordinator :</p>
      <p>credits :</p>
      <p>School :</p>
    </div>
    <div class="">
      <p class="text-black text-truncate">{{courseDetails.name}}</p>
      <p>{{courseDetails.coordinator}}</p>
      <p>{{courseDetails.credits}}</p>
      <p>{{courseDetails.school}}</p>
    </div>

    <div class="position-absolute top-0 end-0 p-2">
      <div class="d-flex gap-1">
        <a href="{% url 'course_app:course_update' courseId=courseDetails.id %}"
          ><i
            class="fa fa-pencil"
            aria-hidden="true"
            style="font-size: 30px"
          ></i
        ></a>

        <form
          action="{% url 'course_app:course_delete' courseId=courseDetails.id %}"
          method="POST"
        >
          {% csrf_token %}
          <button type="submit" class="bg-transparent border-0">
            <i
              class="fa fa-trash"
              aria-hidden="true"
              style="font-size: 30px; color: #a83258"
            >
            </i>
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

course_app/templates/course_edit.html
{% extends 'base.html'%} {% load bootstrap %} {% block body_block %}

<div class="container">
  <h2 class="text-center">Edit Course</h2>
  <div class="container-fluid d-flex justify-content-center">
    <form
      action=""
      id="form"
      method="POST"
      enctype="multipart/form-data"
      class="w-full container-fluid"
    >
      {% csrf_token %} {{course_form|bootstrap_horizontal}}
      <button type="submit" class="btn btn-primary mt-2" name="post_submit">
        post
      </button>
    </form>
  </div>
</div>

{% endblock body_block %}

course_app/templates/course_list.html
{% extends 'base.html'%} {% block body_block %}

<div class="container flex">
  <div class="d-flex justify-content-between align-content-center">
    <h2>Course List</h2>

    <a href="{% url 'course_app:course_create' %}">
      <i
        class="fa fa-plus"
        aria-hidden="true"
        style="color: green; font-size: 35px"
      ></i>
    </a>
  </div>
  {% for course in courseList%}
  <a
    href="{% url 'course_app:course_detail' courseId=course.id%}"
    target="_blank"
    class="text-decoration-none"
  >
    <div class="flex-row flex card p-2 my-3 gap-5 position-relative w-full">
      <div class="">
        <p class="text-black">Name :</p>
        <p>Coordinator :</p>
        <p>credits :</p>
        <p>School :</p>
      </div>
      <div class="">
        <p class="text-black text-truncate">{{course.name}}</p>
        <p>{{course.coordinator}}</p>
        <p>{{course.credits}}</p>
        <p>{{course.school}}</p>
      </div>
      <div class="position-absolute top-0 end-0 p-2">
        <div class="d-flex gap-1">
          <i
            class="fa fa-pencil"
            aria-hidden="true"
            style="font-size: 30px"
          ></i>

          <form
            action="{% url 'course_app:course_delete' courseId=course.id%}"
            method="POST"
          >
            {% csrf_token %}
            <button type="submit" class="bg-transparent border-0">
              <i
                class="fa fa-trash"
                aria-hidden="true"
                style="font-size: 30px; color: #a83258"
              >
              </i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </a>

  {% endfor %}
</div>

{% endblock %}

school_app/templates/school_add.html
{% extends 'base.html'%} {% load bootstrap %} {% block body_block %}

<h2 class="text-center">Add School</h2>
<div class="container-fluid d-flex justify-content-center">
  <div class="container d-flex pt-4 ">
    <form
      action=""
      id="form"
      method="POST"
      class="w-100 w-lg-75 "
   
      enctype="multipart/form-data"
    >
      {% csrf_token %} {{school_form|bootstrap_horizontal}}
      <button type="submit" class="btn btn-primary mt-2  text-center mx-auto" name="post_submit">
        Add School
      </button>
    </form>

    <div class="col-4" style={height:"100vh"}>
      <img
       class="img-fluid object-fit-cover"
        src="https://plus.unsplash.com/premium_photo-1663051241451-709fa4de55bc?q=80&w=2950&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
      />
    </div>
  </div>
</div>

{% endblock body_block %}

school_app/templates/school_detail.html
{% extends 'base.html'%} {% block body_block %}
<div class="container">
  <h2>School Detail Page</h2>
  <div
    class="container flex-row flex card p-2 my-3 gap-5 position-relative w-full"
  >
    <div class="">
      <p class="text-black">Name :</p>
      <p>Head Of School :</p>
      <p>Location :</p>
      <p>Courses :</p>
    </div>
    <div class="">
      <p class="text-black text-truncate">{{schoolDetails.name}}</p>
      <p>{{schoolDetails.head_of_school}}</p>
      <p>{{schoolDetails.location}}</p>
      <ul>
        {% for course in courses %}
        <a href="/course/detail/{{course.id}}">
          <li>{{ course.name }}</li>
        </a>

        {% endfor %}
      </ul>
    </div>

    <div class="position-absolute top-0 end-0 p-2">
      <div class="d-flex gap-1">
        <a href="{% url 'school_app:school_update' schoolId=schoolDetails.id %}"
          ><i
            class="fa fa-pencil"
            aria-hidden="true"
            style="font-size: 30px"
          ></i
        ></a>

        <form
          action="{% url 'school_app:school_delete' schoolId=schoolDetails.id %}"
          method="POST"
        >
          {% csrf_token %}
          <button type="submit" class="bg-transparent border-0">
            <i
              class="fa fa-trash"
              aria-hidden="true"
              style="font-size: 30px; color: #a83258"
            >
            </i>
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

school_app/templates/school_edit.html
{% extends 'base.html'%} {% load bootstrap %} {% block body_block %}
<h2 class="text-center">Edit School</h2>

<div class="container-fluid d-flex justify-content-center">
  <div class="container">
    <form action="" id="form" method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{school_form|bootstrap_horizontal}}
      <button type="submit" class="btn btn-primary mt-2" name="post_submit">
        post
      </button>
    </form>
  </div>
</div>

{% endblock body_block %}

school_app/templates/school_list.html
{% extends 'base.html'%} {% block body_block %}

<div class="container">
  <div class="d-flex justify-content-between align-content-center">
    <h2>School List</h2>
    <a href="{% url 'school_app:school_create' %}">
      <i
        class="fa fa-plus"
        aria-hidden="true"
        style="color: green; font-size: 35px"
      ></i>
    </a>
  </div>
  {% for school in schools%}
  <a
    href="{% url 'school_app:school_detail' schoolId=school.id%}"
    target="_blank"
    class="text-decoration-none text-black"
  >
    <div class="card p-2 my-3 gap-5 position-relative w-full">
      <div class="d-flex gap-3">
        <div class="">
          <p>Name :</p>
          <p>Head Of School :</p>
          <p>Location :</p>
        </div>
        <div class="">
          <p>{{school.name}}</p>
          <p>{{school.head_of_school}}</p>
          <p>{{school.location}}</p>
        </div>
      </div>

      <div class="position-absolute top-0 end-0 p-2">
        <div class="d-flex gap-1">
          <a href="{% url 'school_app:school_update' schoolId=school.id %}">
            <i
              class="fa fa-pencil"
              aria-hidden="true"
              style="font-size: 30px"
            ></i>
          </a>

          <form
            action="{% url 'school_app:school_delete' schoolId=school.id %}"
            method="POST"
          >
            {% csrf_token %}
            <button type="submit" class="bg-transparent border-0">
              <i
                class="fa fa-trash"
                aria-hidden="true"
                style="font-size: 30px; color: #a83258"
              >
              </i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </a>

  {% endfor %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    {% block title %} {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light container">
      <a class="navbar-brand" href="/">My Website</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href={% url 'school_app:school_list' %}>School List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'course_app:course_list' %}>Course List</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid m-0 p-0">
      {% block body_block %} {% endblock %}
    </div>
  </body>
</html>

templates/home.html
{% extends 'base.html'%} {% block body_block %}

<h2>Home Screen</h2>

{% endblock body_block %}